"""Add contraint

Revision ID: 2e2f819b9e4e
Revises: 0c26db595bb1
Create Date: 2022-11-20 19:29:44.097969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e2f819b9e4e"
down_revision = "0c26db595bb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "student_course_contraint", "app__student_course", ["course_id", "student_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "student_course_contraint", "app__student_course", type_="unique"
    )
    # ### end Alembic commands ###
