"""add date mixin

Revision ID: b08697d6f4e3
Revises: 2e2f819b9e4e
Create Date: 2022-11-20 20:53:10.439210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08697d6f4e3'
down_revision = '2e2f819b9e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app__colleges', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('app__colleges', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('app__course', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('app__course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('app__department_batch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('app__department_batch', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('app__student', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('app__student', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('app__student_course', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('app__student_course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app__student_course', 'created_at')
    op.drop_column('app__student_course', 'updated_at')
    op.drop_column('app__student', 'created_at')
    op.drop_column('app__student', 'updated_at')
    op.drop_column('app__department_batch', 'created_at')
    op.drop_column('app__department_batch', 'updated_at')
    op.drop_column('app__course', 'created_at')
    op.drop_column('app__course', 'updated_at')
    op.drop_column('app__colleges', 'created_at')
    op.drop_column('app__colleges', 'updated_at')
    # ### end Alembic commands ###
