version: '2'
services:
  postgress-postgresql:
    image: postgres:14.6
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
    environment:
      - POSTGRES_DB=fastapi-sqlalchemy
      - POSTGRES_USER=joel
      - POSTGRES_PASSWORD=joeljacob
    ports:
      - 9500:5432